/*
 * message_format.h
 *
 *  Created on: May 8, 2025
 *      Author: Bjorn Wakker
 */
#pragma once

#include "lora_app.h"

// Format related defines
#define IDENTIFIER_BYTE 0
#define IDENTIFIER_BYTE_COUNT 1
#define SUBTYPE_BYTE 1
#define SUBTYPE_BYTE_COUNT 1
#define PARAMETERS_START_BYTE 2
#define PARAMETER_MAX_BYTES (LORAWAN_APP_DATA_BUFFER_MAX_SIZE - ((IDENTIFIER_BYTE_COUNT + SUBTYPE_BYTE_COUNT)))

#define MESSAGE_MIN_BYTES (IDENTIFIER_BYTE_COUNT + SUBTYPE_BYTE_COUNT)

// Instruction parameter byte counts
#define BRIGHTNESS_PARAMS_BYTE_COUNT 1
#define BATTERY_VREF_PARAMS_BYTE_COUNT 4
#define TIME_DATE_BYTE_COUNT 9

typedef enum Identifiers
{
	INSTRUCTION_IN = 0xAB,
	RESPONSE_OUT = 0xC0,
	RESPONSE_OUT_WITH_DATA = 0xC1,
	MESSAGE_OUT = 0xD1
} Identifier;

typedef enum InstructionSubtypes
{
	LAMP_OFF = 0x00,
	LAMP_ON = 0x01,
	ACTIVATE_MOTION_SENSOR = 0x02,
	CHANGE_BRIGHTNESS = 0x03,
	SEND_BATTERY_STATUS = 0x04,
	SET_BATTERY_VREFS = 0x05,
	SYNCHRONIZE_TIME_AND_DATE = 0x06,
	SET_TIMESCHEDULE = 0x07,
	SHOW_TIMETABLE = 0x08,
	REMOVE_TIMESCHEDULE = 0x0A
} InstructionSubtype;

typedef enum ResponseSubtypes
{
	INSTRUCTION_COMPLETED = 0x00,
	INVALID_DATA = 0x01,
	MISSING_DATA = 0x02
} ResponseSubtype;

typedef enum ResponseWithDataSubtypes
{
	RESPONDING_TO_INSTRUCTION = 0x00,
	RESPONDING_TO_INSTRUCTION_WARNING = 0x01,
	RESPONDING_TO_INSTRUCTION_ERROR = 0x02
} ResponseWithDataSubtype;

typedef enum Warnings
{
	NO_WARNING = 0x00,
	BATTERY_BELOW_LAMP_MAX_VDD = 0x30,
	MIN_VREF_BELOW_CUTOFF_BOARD = 0x50,
	MIN_VREF_ABOVE_MAX_VDD_BOARD = 0x51,
	MAX_VREF_ABOVE_MAX_VDD_BOARD = 0x52
} Warning;

typedef enum Errors
{
	NO_ERROR = 0x00,
	VREFS_NOT_INITIALIZED = 0x50,
	FAILED_TO_SET_RTC = 0x60,
	SCHEDULE_NOT_FOUND = 0xA0
} Error;
